import * as React from 'react'
import { Link } from 'gatsby'

const CookiesComponent = () => {
    return (
        <>
            <h4>Cookies</h4>
            <p><em>Last updated on 21/01/2023.</em></p>
            <p>This Cookies Policy explains what Cookies are and how We use them. You should read this policy so You can understand what type of cookies We use, or the information We collect using Cookies and how that information is used. This Cookies Policy was generated by TermsFeed Cookies Policy Generator.</p>
            <p>Cookies do not typically contain any information that personally identifies a user, but personal information that we store about You may be linked to the information stored in and obtained from Cookies. For further information on how We use, store and keep your personal data secure, see our Privacy Policy.</p>
            <p>We do not store sensitive personal information, such as mailing addresses, account passwords, etc. in the Cookies We use.</p>
            
            
            <h5>Interpretation and Definitions</h5>
            <p><strong>Interpretation</strong></p>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <p><strong>Definitions</strong></p>
            <p>For the purposes of this Cookies Policy:</p>
            <ul>
                <li>“Company” (referred to as either "the Company", "We", "Us" or "Our" in this Cookies Policy) refers to Polyzentrik Tmi.</li>
                <li>“Cookies” means small files that are placed on Your computer, mobile device or any other device by a website, containing details of your browsing history on that website among its many uses.</li>
                <li>“Website” refers to Polyzentrik’s website, i.e., this website, accessible from http://www.polyzentrik.com and alternative domain forms (including but not limited to https://www.polyzentrik.com, http://polyzentrik.com, and https://polyzentrik.com).</li>
                <li>“You” means the individual accessing or using the Website, or a company, or any legal entity on behalf of which such individual is accessing or using the Website, as applicable.</li>
            </ul>
            
            
            <h5>The use of the Cookies</h5>
            <p><strong>Type of Cookies We Use</strong></p>
            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</p>
            <p>We may use both session and persistent Cookies for the purposes set out below:</p>
            <ul>
                <li> Necessary / Essential Cookies</li>
                <ul>
                    <li>Type: Session Cookies</li>
                    <li>Administered by: Us</li>
                    <li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
                </ul>
            </ul>
            <ul>
                <li>Cookies Policy / Notice Acceptance Cookies</li>
                <ul>
                    <li>Type: Persistent Cookies</li>
                    <li>Administered by: Us</li>
                    <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
                </ul>
            </ul>
            <ul>
                <li>Functionality Cookies</li>
                <ul>
                    <li>Type: Persistent Cookies</li>
                    <li>Administered by: Us</li>
                    <li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
                </ul>
            </ul>
            <ul>
                <li>Tracking and Performance Cookies</li>
                <ul>
                    <li>Type: Persistent Cookies</li>
                    <li>Administered by: Third-Parties</li>
                    <li>Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new advertisements, pages, features or new functionality of the Website to see how our users react to them.</li>
                </ul>
            </ul>


            <h5>Your Choices Regarding Cookies</h5>
            <p>If You prefer to avoid the use of Cookies on the Website, first You must disable the use of Cookies in your browser and then delete the Cookies saved in your browser associated with this website. You may use this option for preventing the use of Cookies at any time.</p>
            <p>If You do not accept Our Cookies, You may experience some inconvenience in your use of the Website and some features may not function properly.</p>
            <p>If You'd like to delete Cookies or instruct your web browser to delete or refuse Cookies, please visit the help pages of your web browser.</p>
            <p>For the Chrome web browser, please visit this page from Google: <Link to="https://support.google.com/accounts/answer/32050" target="_blank" rel="noreferrer" >https://support.google.com/accounts/answer/32050</Link>.</p>
            <p>For the Internet Explorer web browser, please visit this page from Microsoft: <Link to="http://support.microsoft.com/kb/278835" target="_blank" rel="noreferrer">http://support.microsoft.com/kb/278835</Link>.</p>
            <p>For the Firefox web browser, please visit this page from Mozilla: <Link to="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored" target="_blank" rel="noreferrer">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</Link>.</p>
            <p>For the Safari web browser, please visit this page from Apple: <Link to="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" target="_blank" rel="noreferrer">https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac</Link>.</p>
            <p>For any other web browser, please visit your web browser's official web pages.</p>
            <h5>Contact Us</h5>
            <p>If you have any questions about these Terms and Conditions, You can contact us via any of the channels noted in the <Link to="/about">contact</Link> section.</p>
        </>
    )
}

export default CookiesComponent