import * as React from 'react'
import { Link } from 'gatsby'

const DisclaimerComponent = () => {
    return (
        <>
            <h4>Disclaimer</h4>
            <p><em>Last updated on 21/01/2023.</em></p>
            <h5>Interpretation and Definitions</h5>
            <p><strong>Interpretation</strong></p>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <p><strong>Definitions</strong></p>
            <p>For the purposes of this Disclaimer:</p>
            <ul>
                <li>"Company" (referred to as either "the Company", "We", "Us" or "Our" in this Disclaimer) refers to Polyzentrik Tmi.</li>
                <li>"Service" refers to the Website.</li>
                <li>"You" means the individual accessing the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                <li>"Website" refers to Polyzentrik’s website, i.e., this website, accessible from http://www.polyzentrik.com and alternative domain forms (including but not limited to https://www.polyzentrik.com, http://polyzentrik.com, and https://polyzentrik.com).</li>
            </ul>
            <h5>Disclaimer</h5>
            <p>The information contained on the Service is for general information purposes only.</p>
            <p>The Company assumes no responsibility for errors or omissions in the contents of the Service.</p>
            <p>In no event shall the Company be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
            <p>The Company does not warrant that the Service is free of viruses or other harmful components. This Disclaimer was generated by TermsFeed Disclaimer Generator.</p>
            <h5>FTC Affiliate Disclaimer</h5>
            <p>The disclosure that follows is intended to fully comply with the Federal Trade Commission's policy of the United States that requires the Company to be transparent about any and all affiliate relations the Company may have on the Service.</p>
            <p>You should assume that some of the links are "affiliate links", a link with a special tracking code.</p>
            <p>This means that if You click on an affiliate link and purchase the item, the Company may receive an affiliate commission. This is a legitimate way to monetize and pay for the operation of the Service and the Company gladly reveal its affiliate relationships to You.</p>
            <p>Regardless, the Company only recommends products or services the Company believes will add value to users.</p>
            <h5>External Links Disclaimer</h5>
            <p>The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with the Company.</p>
            <p>Please note that the Company does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>
            <h5>Fair Use Disclaimer</h5>
            <p>The Company may use copyrighted material which has not always been specifically authorized by the copyright owner. The Company is making such material available for criticism, comment, news reporting, teaching, scholarship, or research.</p>
            <p>The Company believes this constitutes a "fair use" of any such copyrighted material.</p>
            <p>If You wish to use copyrighted material from the Service for your own purposes that go beyond fair use, You must obtain permission from the copyright owner.</p>
            <h5>Views Expressed Disclaimer</h5>
            <p>The Service may contain views and opinions which are those of the authors and do not necessarily reflect the official policy or position of any other author, agency, organization, employer or company, including the Company.</p>
            <p>Comments published by users are their sole responsibility and the users will take full responsibility, liability and blame for any libel or litigation that results from something written in or as a direct result of something written in a comment. The Company is not liable for any comment published by users and reserves the right to delete any comment for any reason whatsoever.</p>
            <h5>No Responsibility Disclaimer</h5>
            <p>The information on the Service should not be used as a substitute for consultation with professional accounting, tax, legal or other competent advisers.</p>
            <p>In no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever arising out of or in connection with your access or use or inability to access or use the Service.</p>
            <h5>"Use at Your Own Risk" Disclaimer</h5>
            <p>All information in the Service is provided "as is", with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose.</p>
            <p>The Company will not be liable to You or anyone else for any decision made or action taken in reliance on the information given by the Service or for any consequential, special or similar damages, even if advised of the possibility of such damages.</p>
            <h5>Contact Us</h5>
            <p>If you have any questions about these Terms and Conditions, You can contact us via any of the channels noted in the <Link to="/about">contact</Link> section.</p>

        </>
    )
}

export default DisclaimerComponent