import * as React from 'react'
import { Link } from 'gatsby'

const PrivacyComponent = () => {
    return (
        <>
            <h4> Privacy Policy </h4>
            <p>Our Privacy Policy was last updated on 11/08/2023. The Policy was adapted from a policy generated by TermsFeed GDPR Privacy Policy Generator.</p>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We may ause Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. </p>
            <h5> Interpretation and Definitions </h5>
            <p><strong> Interpretation </strong></p>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
            <p><strong> Definitions </strong></p>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li>“Account” means a unique account created for You to access our Service or parts of our Service.</li>
                <li>“Company” (referred to as either “the Company”, “I”, “We”, “Us”, or “Our” in this Agreement) refers to Polyzentrik Tmi.</li>
            </ul>
            <p>For the purpose of the GDPR, the Company is the Data Controller.</p>
            <ul>
                <li>“Country” refers to Finland.</li>
                <li>“Cookies” are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li>“Data Controller”, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</li>
                <li>“Device” means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                <li>“Personal Data” is any information that relates to an identified or identifiable individual. For the purposes of GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity.</li>
                <li>“Service” refers to the Website.</li>
                <li>“Service Provider” means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.</li>
                <li>“Usage Data” refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li>“Website” refers to Polyzentrik’s website, i.e., this website, accessible from http://www.polyzentrik.com and alternative domain forms (including but not limited to https://www.polyzentrik.com, http://polyzentrik.com, and https://polyzentrik.com).</li>
                <li>“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
            <p>Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.</p>
            <h5> Collecting and Using Your Personal Data </h5>
            <p><strong> Types of Data Collected </strong></p>
            <p><em> Personal Data </em></p>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. </p>
            <p>Personally identifiable information may include, but is not limited to:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
            </ul>
            <p>We do not currently ask for any of this information. However, we do reserve the right to ask You for this information. If We do so, however, We will specify the reasons We ask for the information and ask for Your consent.</p>
            <p><em> Usage Data </em></p>
            <p>Usage Data may be collected automatically when using the Service, for instance but not exclusively, in the context of SEO analytics. Usage Data may be collected by Us or by a Service Provider.</p>
            <p>Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We and Service Providers may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We and Service Providers may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <p><em> Tracking Technologies and Cookies </em></p>
            <p>Our use of Cookies is detailed in Our Cookies Policy. We approach Cookies on a 'need-to-know' basis. By agreeing to this Privacy Policy You agree we may use Cookies to collect Your data. Cookies are needed in a wide variety of settings and, as such, We need to reserve the right to use Cookies. However, We do our best to minimise the use of Cookies and strive to only use Cookies to collect data we need (as opposed to collecting data indiscriminately "just in case" we can monetise it). The Cookies section contains information about the specific Data We currently collect via Cookies.</p>
            <h5> Use of Your Personal Data </h5>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
            </ul>
            <p>We may share Your personal information in the following situations:</p>
            <ul>
                <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.</li>
                <li>For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                <li>With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                <li>With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                <li>With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
            </ul>
            <h5> Retention of Your Personal Data </h5>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>The Company and any providers or partners with whom data is shared also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods. That said, since we are a small company and some providers of website analytics are huge corporations that do not respond to us, we have no control over how long your data may be retained by them.</p>
            <h5> Transfer of Your Personal Data </h5>
            <p>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
            <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
            <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
            <h5> Disclosure of Your Personal Data </h5>
            <p><strong> Business Transactions </strong></p>
            <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            <p><strong> Law enforcement </strong></p>
            <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            <p><strong> Other legal requirements </strong></p>
            <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
            </ul>
            <h5> Security of Your Personal Data </h5>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            <h5> Detailed Information on the Processing of Your Personal Data </h5>
            <p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
            <p><strong> Analytics </strong></p>
            <p>We may use third-party Service providers to monitor and analyze the use of our Service.</p>
            <p><strong> Email Marketing </strong></p>
            <p>We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt out of receiving any or all of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.</p>
            <p><strong> Payments </strong></p>
            <p>We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).</p>
            <p>We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. </p>
            <p>While we cannot guarantee the security of any third-party system and reserve the right to change payment provider under our discretion, We strive to use only reputable payment providers.</p>
            <h5> GDPR Privacy Policy </h5>
            <p><strong> Legal Basis for Processing Personal Data under GDPR </strong></p>
            <p>We may process Personal Data under the following conditions:</p>
            <ul>
                <li>Consent: You have given Your consent for processing Personal Data for one or more specific purposes.</li>
                <li>Performance of a contract: Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
                <li>Legal obligations: Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
                <li>Vital interests: Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
                <li>Public interests: Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
                <li>Legitimate interests: Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
            </ul>
            <p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>
            <p><strong> Your Rights under the GDPR </strong></p>
            <p>The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.</p>
            <p>You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>
            <ul>
                <li>Request access to Your Personal Data. The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.</li>
                <li>Request correction of the Personal Data that We hold about You. You have the right to have any incomplete or inaccurate information We hold about You corrected.</li>
                <li>Object to processing of Your Personal Data. This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.</li>
                <li>Request erasure of Your Personal Data. You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</li>
                <li>Request the transfer of Your Personal Data. We will provide to You, or to a third party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.</li>
                <li>Withdraw Your consent. You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.</li>
            </ul>
            <p><strong> Exercising of Your GDPR Data Protection Rights </strong></p>
            <p>You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.</p>
            <p>You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.</p>
            <h5> Children’s Privacy </h5>
            <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
            <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.</p>
            <h5> Links to Other Websites </h5>
            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third-party’s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>
            <h5> Changes to this Privacy Policy </h5>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
            <p>If your data is affected by a change to our Privacy Policy, We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            <h5> Contact Us </h5>
            <p>If you have any questions about these Terms and Conditions, You can contact us via any of the channels noted in Our <Link to='/about/'>About & Contact section</Link>.</p>
        </>
    )
}

export default PrivacyComponent