import * as React from 'react'
import { Link } from 'gatsby'

const TermsComponent = () => {
    return (
        <>
            <h4>Terms and Conditions (“Terms”)</h4>
            <p>Our Terms and Conditions were last updated on 09/08/2023. The Policy was adapted from a TermsFeed Sample Terms And Conditions.</p>
            <h5>Interpretation and Definitions</h5>
            <p><strong>Interpretation</strong></p>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
            <p><strong>Definitions</strong></p>
            <p>For the purposes of these Terms and Conditions:</p>
            <ul>
                <li>“Company” (referred to as either “the Company”, “We”, “Us”, or “Our” in this Agreement) refers to Polyzentrik Tmi.</li>
                <li>“Country” refers to Finland.</li>
                <li>“Content” refers to Content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available to or by You, regardless of the form of that Content.</li>
                <li>“Device” means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li>“Feedback” means feedback, innovations or suggestions sent by You regarding the attributes, performance or features of our Service.</li>
                <li>“Products” refer to the goods and services offered on the Service.</li>
                <li>“Orders” mean a request by You to purchase Products from Us.</li>
                <li>“Payments” mean a request by You to pay to Us.</li>
                <li>“Donations” mean a request by You to donate to Us.</li>
                <li>“Promotions” refer to contests, sweepstakes or other promotions offered through the Service.</li>
                <li>“Service” refers to the Website.</li>
                <li>“Terms and Conditions” (also referred to as “Terms”) mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated by TermsFeed Terms and Conditions Generator.</li>
                <li>“Third-party Social Media Service” means any services or Content (including data, information, products or services) provided by a third party that may be displayed, included or made available by the Service.</li>
                <li>“Website” refers to Polyzentrik’s Website, i.e., this Website, accessible from http://www.polyzentrik.com and alternative domain forms (including but not limited to https://www.polyzentrik.com, http://polyzentrik.com, and https://polyzentrik.com).</li>
                <li>“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
            <h5>Acknowledgment</h5>
            <p>These are the Terms and Conditions governing the use of this Service and the Agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
            <p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
            <p>By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.</p>
            <p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
            <p>Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.</p>
            <h5>User Accounts</h5>
            <p>We do not currently offer user accounts.</p>
            <h5>Content</h5>
            <p><strong>Your Right to Send and have Content posted</strong></p>
            <p>Our Service does not currently allow You to directly post Content but We accept and might publish Content You send to Us.</p>
            <p>If You send Us Content for publishing and We publish it, You are responsible for the Content that You send, including its legality, reliability, and appropriateness. Additionally, You grant Us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. We will endeavour to maintain the integrity of the intended message. However, we absolutely need this right as above to be able to use the Content throughout the Service, for instance but not exclusively, in previews and as part of meta-data for social media previews.</p>
            <p>You retain any and all of Your rights to any Content You submit, post or display on or through the Service and You are responsible for protecting those rights.</p>
            <p>You agree that this license includes the right for Us to make Your Content available to other users of the Service, who may also use Your Content subject to these Terms.</p>
            <p>You represent and warrant that: (i) the Content is Yours (You own it) or You have the right to use it and grant Us the rights and license as provided in these Terms, and (ii) the posting of Your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person.</p>
            <p>Content Restrictions</p>
            <p>The Company is not responsible for the Content of the Service’s users. You expressly understand and agree that You are solely responsible for the Content you send or otherwise make available to us for publishing.</p>
            <p>You may not transmit any Content that is unlawful, offensive, upsetting, intended to disgust, threatening, libellous, defamatory, obscene or otherwise objectionable. Examples of such objectionable Content include, but are not limited to, the following:</p>
            <ul>
                <li>Unlawful or promoting unlawful activity.</li>
                <li>Defamatory, discriminatory, or mean-spirited Content, including references or commentary about religion, race, sexual orientation, gender, national/ethnic origin, or other targeted groups.</li>
                <li>Spam, machine – or randomly – generated, constituting unauthorized or unsolicited advertising, chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling.</li>
                <li>Containing or installing any viruses, worms, malware, trojan horses, or other Content that is designed or intended to disrupt, damage, or limit the functioning of any software, hardware or telecommunications equipment or to damage or obtain unauthorized access to any data or other information of a third person.</li>
                <li>Infringing on any proprietary rights of any party, including patent, trademark, trade secret, copyright, right of publicity or other rights.</li>
                <li>Impersonating any person or entity including the Company and its employees or representatives.</li>
                <li>Violating the privacy of any third person.</li>
                <li>False information and features.</li>
            </ul>
            <p>The Company reserves the right, but not the obligation, to, in its sole discretion, determine whether or not any Content is appropriate and complies with this Terms, refuse or remove this Content.</p>
            <p>The Company further reserves the right to make formatting and edits and change the manner of any Content. This right will not be used to intentionally change the meaning of Your input but is needed to ensure We can format and edit objectionable Content. An example is objectionable Content by a participant in a recorded event, which often cannot be removed without slightly altering/shortening statements by other participants. However, since it is impossible for Us to foresee all specific situations requiring formatting and editing, We need to reserve this right in general and as expressed in the first sentence of this paragraph.</p>
            <p>The Company can also limit or revoke the use of the Service if You send or otherwise post such objectionable Content. As the Company cannot control all Content sent or otherwise posted by users and/or third parties on the Service nor ensure that Content does not trigger personal susceptibilities, you agree to use the Service at your own risk. You understand that by using the Service You may be exposed to Content that You may find offensive, indecent, incorrect or objectionable, and You agree that under no circumstances will the Company be liable in any way for any content, including any errors or omissions in any content, or any loss or damage of any kind incurred as a result of your use of any content.</p>
            <p><strong>Content Backups</strong></p>
            <p>Although regular backups of Content are performed, the Company does not guarantee there will be no loss or corruption of data.</p>
            <p>Corrupt or invalid backup points may be caused by, without limitation, Content that is corrupted prior to being backed up or that changes during the time a backup is performed.</p>
            <p>The Company will provide support and attempt to troubleshoot any known or discovered issues that may affect the backups of Content. But You acknowledge that the Company has no liability related to the integrity of Content or the failure to successfully restore Content to a usable state.</p>
            <p>You agree to maintain a complete and accurate copy of any Content in a location independent of the Service.</p>
            <h5>Copyright Policy</h5>
            <p><strong>Intellectual Property Infringement</strong></p>
            <p>We respect the intellectual property rights of others. It is Our policy to respond to any claim that Content posted on the Service infringes a copyright or other itellectual property infringement of any person.</p>
            <p>If You are a copyright owner, or authorized on behalf of one, and You believe that the copyrighted work has been copied in a way that constitutes copyright infringement that is taking place through the Service, You must submit Your notice in writing to the attention of our copyright agent via email (hello@polyzentrik.com) and include in Your notice a detailed description of the alleged infringement.</p>
            <p>You may be held accountable for damages (including costs and attorneys’ fees) for misrepresenting that any Content is infringing Your copyright.</p>
            <p><strong>DMCA Notice and DMCA Procedure for Copyright Infringement Claims</strong></p>
            <p>You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
            <ul>
                <li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright’s interest.</li>
                <li>A description of the copyrighted work that You claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work.</li>
                <li>Identification of the URL or other specific location on the Service where the material that You claim is infringing is located.</li>
                <li>Your address, telephone number, and email address.</li>
                <li>A statement by You that You have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.</li>
                <li>A statement by You, made under penalty of perjury, that the above information in Your notice is accurate and that You are the copyright owner or authorized to act on the copyright owner’s behalf.</li>
            </ul>
            <p>You can contact our copyright agent via email (hello@polyzentrik.com). Upon receipt of a notification, the Company will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged Content from the Service.</p>
            <h5>Placing Orders for Products</h5>
            <p>By placing an Order or making a Payment or Donation through the Service, You warrant that You are legally capable of entering into binding contracts.</p>
            <p>You acknowledge and agree that We do not currently offer Products that can be purchased online in advance and that our online payments gateway is there to facilitate payment by users who have already received a Product and enable Donations by users wishing to contribute to our work. Accordingly, You also agree that:</p>
            <ul>
                <li>You cannot book or reserve services by placing an Order, Pay</li>
                <li>We do not guarantee the availability of any Product offered in our Service</li>
                <li>You will not use the online payments gateway unless you have already received a Product and been asked to place a payment via the Website or otherwise agreed with Us to make a Payment through the Website.</li>
            </ul>
            <p><strong>Your Information</strong></p>
            <p>If You place an Order, Payment, or Donation on the Service, You may be re-directed to a third party that will ask you to supply certain information relevant to Your Order including, without limitation, Your name, Your email, Your phone number, Your credit card number, the expiration date of Your credit card, Your billing address, and Your shipping information.</p>
            <p>You represent and warrant that: (i) You have the legal right to use any credit or debit card(s) or other payment method(s) in connection with any Order; and that (ii) the information You supply is true, correct and complete.</p>
            <p>By submitting this information You also accept any additional policies required by the third party. We will endeavour to use reliable payment providers, but You need to decide if You accept their terms separately because we do not have control over them. If you do not agree to their terms, do not place the Order, Payment, or Donation and get in touch with Us to arrange a different form of payment.</p>
            <p><strong>Order Cancellation</strong></p>
            <p>If you make an Order, Payment, or Donation believing this guarantees Product availability and We cannot or do not wish to fulfil the Order, we will treat the matter as an Order cancellation. In such an event, You accept that we will strive but are under no obligation to refund you the Payment minus fees incurred.</p>
            <p><strong>Your Order Cancellation Rights</strong></p>
            <p>Any Products You purchase can only be returned or refunded in accordance with these Terms and Conditions.</p>
            <p><strong>Availability, Errors and Inaccuracies</strong></p>
            <p>By using the Service You agree and acknowledge that mistakes happen.</p>
            <p>While We aim to avoid any problems with the Service, Products available on Our Service may be mispriced, described inaccurately, or unavailable, and We may experience delays in updating information regarding our Products on the Service and in Our advertising on other websites.</p>
            <p>We cannot and do not guarantee the accuracy or completeness of any information, including prices, product images, specifications, availability, and services. We reserve the right to change or update information and to correct errors, inaccuracies, or omissions at any time without prior notice.</p>
            <p><strong>Prices Policy</strong></p>
            <p>The Company reserves the right to revise its prices at any time prior to accepting an Order.</p>
            <p>The prices quoted may be revised by the Company subsequent to accepting an Order in the event of any occurrence affecting delivery caused by government action, variation in customs duties, increased shipping charges, higher foreign exchange costs and any other matter beyond the control of the Company. In that event, You will have the right to cancel Your Order.</p>
            <p><strong>Payments</strong></p>
            <p>Payments are subject to validation checks and authorization by Your card issuer or financial provider. If we do not receive the required authorization, We will not be liable for any delay or non-delivery of Your Order.</p>
            <p><strong>Promotions</strong></p>
            <p>Any Promotions made available through the Service may be governed by rules that are separate from these Terms. If You participate in any Promotions, please review the applicable rules as well as our Privacy policy. If the rules for a Promotion conflict with these Terms, the Promotion rules will apply.</p>
            <h5>Intellectual Property</h5>
            <p>The Service and its original Content (excluding Content provided by You or other users), features and functionality are and will remain the exclusive property of the Company and its licensors.</p>
            <p>Some resources We publish or make available through the Service are governed by open-source licenses. In such cases, the term “licensors” may cover You. We strive to ensure all open-source resources are clearly marked. That said, You agree to review the license of any resource you find through our Service.</p>
            <p>The Service is protected by copyright and other laws of both the Country and foreign countries.</p>
            <p>Our name, logos, copyrighted material, and/or any trademarks may not be used in connection with any product or Service without the prior written consent of the Company.</p>
            <h5>Your Feedback to Us</h5>
            <p>You assign all rights, title and interest in any Feedback You provide the Company. If for any reason such assignment is ineffective, You agree to grant the Company a non-exclusive, perpetual, irrevocable, royalty free, worldwide right and license to use, reproduce, disclose, sub-license, distribute, modify and exploit such Feedback without restriction.</p>
            <h5>Links to Other Websites</h5>
            <p>Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.</p>
            <p>The Company has no control over, and assumes no responsibility for, the Content, privacy policies, or practices of any third-party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
            <p>We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.</p>
            <h5>Termination</h5>
            <p>We may terminate or suspend Your Account or access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.</p>
            <p>Upon termination, Your right to use the Service will cease immediately. If You wish to terminate Your Account, You may simply discontinue using the Service.</p>
            <h5>Limitation of Liability</h5>
            <p>Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 1 EURO if You haven’t purchased anything through the Service.</p>
            <p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
            <p>Some jurisdictions may not allow the exclusion of certain types of liabilities, so some or all of the above may not be applicable to You. In such a case the limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
            <h5>“AS IS” and “AS AVAILABLE” Disclaimer</h5>
            <p>The Service is provided to You “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error-free or that any errors or defects can or will be corrected.</p>
            <p>Without limiting the foregoing, neither the Company nor any of the Company’s providers makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, Content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or Content provided through the Service; or (iv) that the Service, its servers, the Content, or emails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
            <p>Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
            <h5>Governing Law</h5>
            <p>The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
            <h5>Disputes Resolution</h5>
            <p>If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
            <h5>For European Union (EU) Users</h5>
            <p>If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which you are resident in.</p>
            <h5>United States Legal Compliance</h5>
            <p>You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a “terrorist supporting” country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
            <h5>Severability and Waiver</h5>
            <p><strong>Severability</strong></p>
            <p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
            <p><strong>Waiver</strong></p>
            <p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Terms shall not effect a party’s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute a waiver of any subsequent breach.</p>
            <h5>Changes to These Terms and Conditions</h5>
            <p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days’ notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.</p>
            <p>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the Website and the Service.</p>
            <h5>Contact Us</h5>
            <p>If you have any questions about these Terms and Conditions, You can contact us via any of the channels noted in Our <Link to="/about/">About & Contact section</Link>.</p>
        </>
    )
}

export default TermsComponent